networks:
  api:
    name: api
    external: false

services:
  VivaItaliana:
    container_name: VivaItaliana
    image: php-apache-composer
    build:
      context: .
      target: php-apache-composer
      dockerfile: Dockerfile
    volumes: 
      - ./app:/var/www/html
      - ./db:/var/www/db
      - ./llm:/llm/
    ports: 
      - 80:80
      - 443:443
    networks:
      - api

  rasa:
    image: rasa/rasa:3.6.21-full
    volumes:
      - ./llm:/app
    entrypoint: "sleep infinity"
    networks:
      - api

