version: "3.0"
services:
  deepseek:
    container_name: deepseek
    image: deepseek
    build:
      context: .
      target: deepseek
      dockerfile: Dockerfile
    volumes: 
      - ./:/app
    ports: 
      - 80:80
      - 443:443

