version: "3.0"
services:
  VivaItaliana:
    container_name: VivaItaliana
    image: php-apache-composer
    build:
      context: .
      target: php-apache-composer
      dockerfile: Dockerfile
    volumes: 
      - ./app:/var/www/html
      - ./db:/var/www/db
    ports: 
      - 80:80
      - 443:443

